# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."enc".device =
    "/dev/disk/by-uuid/336722f6-ac06-45ca-a291-1cd78f35548c";

  fileSystems."/" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd" "noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=zstd" "noatime" ];
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=persist" "compress=zstd" "noatime" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=log" "compress=zstd" "noatime" ];
  };

  fileSystems."/snapshots" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=snapshots" "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/59D5-28C2";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Windows partitions - Managed by udisks2 for on-demand mounting
  # They will appear in Nautilus "Other Locations" with mount/unmount buttons
  # and size information. Uncomment below to auto-mount at boot instead:
  #
  # fileSystems."/mnt/windows-c" = {
  #   device = "/dev/disk/by-partuuid/508b2268-cfc5-4e07-b7db-473693a80f6e";
  #   fsType = "ntfs-3g";
  #   options = [ "rw" "uid=1000" "gid=100" "umask=0022" "nofail" "x-systemd.device-timeout=10" ];
  # };
  #
  # fileSystems."/mnt/windows-d" = {
  #   device = "/dev/disk/by-partuuid/727dd306-3aec-419b-844d-7a8bd5500c9c";
  #   fsType = "ntfs-3g";
  #   options = [ "rw" "uid=1000" "gid=100" "umask=0022" "nofail" "x-systemd.device-timeout=10" ];
  # };
  #
  # fileSystems."/mnt/windows-e" = {
  #   device = "/dev/disk/by-partuuid/3d91ad77-a81a-466f-b224-3cc2def241c4";
  #   fsType = "ntfs-3g";
  #   options = [ "rw" "uid=1000" "gid=100" "umask=0022" "nofail" "x-systemd.device-timeout=10" ];
  # };


  swapDevices = [
    { device = "/dev/disk/by-uuid/5d0b9a9e-bb2b-4189-be05-49b231acad3b"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
